name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn  test
  build:
    needs: ['tests']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache with Local Repository
      uses: actions/cache@v4.0.2
      with:
       path: ~/.m2
      # An explicit key for restoring and saving the cache
       key: ${{ runner.os }}-maven-
      # An order list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
       restore-keys: ${{runner.os}}-maven-
      # The chunk size used to split up large files during upload, in bytes
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
       name: artifact

